<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE beans [
        <!ELEMENT beans (context:component-scan|context:annotation-config|cache:annotation-driven|bean)*>
        <!ATTLIST beans
                xmlns:xsi CDATA #REQUIRED
                xmlns CDATA #REQUIRED
                xmlns:aop CDATA #REQUIRED
                xmlns:context CDATA #REQUIRED
                xmlns:tx CDATA #REQUIRED
                xmlns:cache CDATA #REQUIRED
                xmlns:p CDATA #REQUIRED
                xsi:schemaLocation CDATA #REQUIRED>
        <!ELEMENT context:component-scan (#PCDATA)>
        <!ATTLIST context:component-scan
                base-package CDATA #REQUIRED>
        <!ELEMENT context:annotation-config (#PCDATA)>
        <!ELEMENT cache:annotation-driven (#PCDATA)>
        <!ELEMENT bean (property)*>
        <!ATTLIST bean
                class CDATA #REQUIRED
                id CDATA #IMPLIED>
        <!ELEMENT property (set)*>
        <!ATTLIST property
                name CDATA #REQUIRED
                value CDATA #IMPLIED>
        <!ELEMENT set (bean)*>
        ]>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.springframework.org/schema/beans" xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:context="http://www.springframework.org/schema/context" xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:cache="http://www.springframework.org/schema/cache" xmlns:p="http://www.springframework.org/schema/p"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
     http://www.springframework.org/schema/beans/spring-beans-4.0.xsd
     http://www.springframework.org/schema/aop
     http://www.springframework.org/schema/aop/spring-aop-4.0.xsd
     http://www.springframework.org/schema/context
     http://www.springframework.org/schema/context/spring-context-4.0.xsd
     http://www.springframework.org/schema/tx
     http://www.springframework.org/schema/tx/spring-tx-4.0.xsd
     http://www.springframework.org/schema/cache http://www.springframework.org/schema/cache/spring-cache-4.0.xsd">

    <context:component-scan base-package="top.mineor"/>

    <context:annotation-config/>

    <cache:annotation-driven/>

    <bean id="cacheManager" class="org.springframework.cache.support.SimpleCacheManager">
        <property name="caches">
            <set>
                <bean class="org.springframework.cache.concurrent.ConcurrentMapCacheFactoryBean">
                    <property name="name" value="default"/>
                </bean>
                <bean class="org.springframework.cache.concurrent.ConcurrentMapCacheFactoryBean">
                    <property name="name" value="accountCache"/>
                </bean>
            </set>
        </property>
    </bean>



</beans>